### ISSUE TITLE
Blog 反馈

### ISSUE THREAD

**Issue by the0demiurge** [shell909090/shell909090.github.io#1]
内容写得十分吸引人，但是一篇文章只有一个段落，阅读起来十分痛苦

**Comment by shell909090** [comment]
你看一眼这个URL，也是一个段落？
http://blog.shell909090.org/blog/archives/2868/

**Comment by the0demiurge** [comment]
原来是主页上的预览内容没有截断，我把主页上的预览内容当成了正文。。
