### ISSUE TITLE
关于goproxy分支的问题

### ISSUE THREAD

**Issue by jm33-m0** [shell909090/shell909090.github.io#2]
首先对冒昧在你博客repo下开issue表示歉意（随后你可以删除），但我没有找到其他联系方式。

事情很奇怪，我不知什么时候fork过[goproxy](https://github.com/justzx2011/goproxy)项目，它目前的链接指向似乎是某个fork的分支，最后一次更新停留在2013年，是你提交的。

我注意到这个事情是因为[https://github.com/888001](https://github.com/888001)用户给我fork的goproxy项目打了star。我点进去发现我fork的repo居然比原repo还领先200多个commit，于是我点进去fork network，发现自己的fork已经是主分支了。

![image](https://user-images.githubusercontent.com/10167884/102181552-c183b800-3ee5-11eb-8675-38be71700bfb.png)

我在你的repo列表里面没有发现goproxy这个项目，所以我猜测你是它的原作者，且已经从自己的账户下删除了它的repo。

没有其他意思，我主要是想搞清楚这个bug的原理，以及是否可以复现它。可能的话，我们也可以当作安全漏洞提交。

**Comment by shell909090** [comment]
哦，没事。
这个原因非常简单。我首先将goproxy的主br改为了第一个空的commit。这样所有爬虫抓到的就是一个空项目。这也是你为什么看到你fork的br比主br领先200多个commits的原因。但实际上我项目中的master和dev两个br还在进一步走。（而不是main br）
去年进一步收紧后，我就把项目私有化了。因此你后来就找不到这个项目了。

**Comment by jm33-m0** [comment]
看来是我理解出现了偏差，我的并不是主分支😂
既然是符合预期的，那就不是bug，我关了issue了
